/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next/components/BButton')['BButtonGroup']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormInvalidFeedback: typeof import('bootstrap-vue-next/components/BForm')['BFormInvalidFeedback']
    BFormRadio: typeof import('bootstrap-vue-next/components/BFormRadio')['BFormRadio']
    BFormRadioGroup: typeof import('bootstrap-vue-next/components/BFormRadio')['BFormRadioGroup']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BIconArrow90degUp: typeof import('~icons/bi/arrow90deg-up')['default']
    BIconArrowLeft: typeof import('~icons/bi/arrow-left')['default']
    BIconArrowLeftRight: typeof import('~icons/bi/arrow-left-right')['default']
    BIconArrowUpRightSquare: typeof import('~icons/bi/arrow-up-right-square')['default']
    BIconBoxArrowUpRight: typeof import('~icons/bi/box-arrow-up-right')['default']
    BIconBricks: typeof import('~icons/bi/bricks')['default']
    BIconCheck: typeof import('~icons/bi/check')['default']
    BIconCheckSquare: typeof import('~icons/bi/check-square')['default']
    BIconChevronDown: typeof import('~icons/bi/chevron-down')['default']
    BIconChevronRight: typeof import('~icons/bi/chevron-right')['default']
    BIconDatabase: typeof import('~icons/bi/database')['default']
    BIconDownload: typeof import('~icons/bi/download')['default']
    BIconExclamationTriangle: typeof import('~icons/bi/exclamation-triangle')['default']
    BIconEye: typeof import('~icons/bi/eye')['default']
    BIconFileEarmarkRichtext: typeof import('~icons/bi/file-earmark-richtext')['default']
    BIconFilter: typeof import('~icons/bi/filter')['default']
    BIconFlag: typeof import('~icons/bi/flag')['default']
    BIconFolderMinus: typeof import('~icons/bi/folder-minus')['default']
    BIconFolderPlus: typeof import('~icons/bi/folder-plus')['default']
    BIconFolderSymlink: typeof import('~icons/bi/folder-symlink')['default']
    BIconInfoLg: typeof import('~icons/bi/info-lg')['default']
    BIconLayersFill: typeof import('~icons/bi/layers-fill')['default']
    BIconList: typeof import('~icons/bi/list')['default']
    BIconListTask: typeof import('~icons/bi/list-task')['default']
    BIconLock: typeof import('~icons/bi/lock')['default']
    BIconMoonStars: typeof import('~icons/bi/moon-stars')['default']
    BIconPinMapFill: typeof import('~icons/bi/pin-map-fill')['default']
    BIconSearch: typeof import('~icons/bi/search')['default']
    BIconShare: typeof import('~icons/bi/share')['default']
    BIconSortAlphaDown: typeof import('~icons/bi/sort-alpha-down')['default']
    BIconSortAlphaUp: typeof import('~icons/bi/sort-alpha-up')['default']
    BIconSquare: typeof import('~icons/bi/square')['default']
    BIconSun: typeof import('~icons/bi/sun')['default']
    BIconThreeDots: typeof import('~icons/bi/three-dots')['default']
    BIconX: typeof import('~icons/bi/x')['default']
    BIconXCircleFill: typeof import('~icons/bi/x-circle-fill')['default']
    BIconZoomIn: typeof import('~icons/bi/zoom-in')['default']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BListGroup: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroupItem']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vBToggle: typeof import('bootstrap-vue-next/directives/BToggle')['vBToggle']
  }
}
